{
    "token": 'Z13cPZBhxyTxStQJJ9ejrg6PMq_eBe6iK0TH056XHCTu3OtTSt0IdonZj46m0F59RCZT24Fyc4Ef_eXEAzXG_D9lJcEsCiZ4JdsKvfyCJDaqqE_Iaqx9XWT3',
    "study_id": '6719fde3ab4119a32b2db2a2',
    "max_concurrent_sessions": 13,
    "workload_checker_period": 60
}